### ISSUE TITLE
Access log with mysql db throws error

### ISSUE THREAD

**Issue by santoshbmath** [freakchick/DBApi#34]
Hi,

When i enabled access log with mysql db, i am getting following error,

```
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Every derived table must have its own alias
### The error may exist in com/gitee/freakchicken/dbapi/basic/dao/AccessLogMapper.java (best guess)
### The error may involve com.gitee.freakchicken.dbapi.basic.dao.AccessLogMapper.top5api-Inline
### The error occurred while setting parameters
### SQL: select url,num from (select url,count(1) num from access_log where timestamp >= ? and timestamp < ? group by url) order by num desc limit 0,10
### Cause: java.sql.SQLSyntaxErrorException: Every derived table must have its own alias
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Every derived table must have its own alias] with root cause
java.sql.SQLSyntaxErrorException: Every derived table must have its own alias
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3051)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:67)
```

Thanks,
Santosh

**Comment by freakchick** [comment]
do you use version 3.2.0 ? 
That is bug in 3.2.0 ! Please use 3.2.1 version

**Comment by RainbowWS** [comment]
```select url,num from (select url,count(1) num from access_log group by url) as a order by num desc limit 0,10```
need add alias to  ```(select url,count(1) num from access_log group by url) ``` as a.
solve the problem.

**Comment by santoshbmath** [comment]
@freakchick , yes i am using version 3.2.0. I will try to switch to 3.2.1 and see if issue gets resolved.

**Comment by santoshbmath** [comment]
After upgrading to 3.2.1, the issue is resolved. Closing the issue. 

Thanks for your help.
